 create table company_register
 (
     company_id int8 generated by default as identity,
      company_name varchar(200) not null ,
      country varchar(200) not null ,
      primary key (company_id)
 );
